<?php
/**
 * HistoryItem
 *
 * PHP version 7.1.3
 *
 * @category Class
 * @package  OpenAPI\Server\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Password Manager
 *
 * This is a password manager server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: test@te.st
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the HistoryItem model.
 *
 * @package OpenAPI\Server\Model
 * @author  OpenAPI Generator team
 */
class HistoryItem 
{
        /**
     * @var string|null
     * @SerializedName("UserAgent")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $userAgent;

    /**
     * @var string|null
     * @SerializedName("IP")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $iP;

    /**
     * @var \DateTime|null
     * @SerializedName("Time")
     * @Assert\DateTime()
     * @Type("DateTime")
     */
    protected $time;

    /**
     * @var string|null
     * @SerializedName("Event")
     * @Assert\Choice({ "Login", "ChangePassword", "Registration" })
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $event;

    /**
     * @var string|null
     * @SerializedName("EventResult")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $eventResult;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->userAgent = isset($data['userAgent']) ? $data['userAgent'] : null;
        $this->iP = isset($data['iP']) ? $data['iP'] : null;
        $this->time = isset($data['time']) ? $data['time'] : null;
        $this->event = isset($data['event']) ? $data['event'] : null;
        $this->eventResult = isset($data['eventResult']) ? $data['eventResult'] : null;
    }

    /**
     * Gets userAgent.
     *
     * @return string|null
     */
    public function getUserAgent()
    {
        return $this->userAgent;
    }

    /**
     * Sets userAgent.
     *
     * @param string|null $userAgent
     *
     * @return $this
     */
    public function setUserAgent($userAgent = null)
    {
        $this->userAgent = $userAgent;

        return $this;
    }

    /**
     * Gets iP.
     *
     * @return string|null
     */
    public function getIP()
    {
        return $this->iP;
    }

    /**
     * Sets iP.
     *
     * @param string|null $iP
     *
     * @return $this
     */
    public function setIP($iP = null)
    {
        $this->iP = $iP;

        return $this;
    }

    /**
     * Gets time.
     *
     * @return \DateTime|null
     */
    public function getTime(): ?\DateTime
    {
        return $this->time;
    }

    /**
     * Sets time.
     *
     * @param \DateTime|null $time
     *
     * @return $this
     */
    public function setTime(\DateTime $time = null)
    {
        $this->time = $time;

        return $this;
    }

    /**
     * Gets event.
     *
     * @return string|null
     */
    public function getEvent()
    {
        return $this->event;
    }

    /**
     * Sets event.
     *
     * @param string|null $event
     *
     * @return $this
     */
    public function setEvent($event = null)
    {
        $this->event = $event;

        return $this;
    }

    /**
     * Gets eventResult.
     *
     * @return string|null
     */
    public function getEventResult()
    {
        return $this->eventResult;
    }

    /**
     * Sets eventResult.
     *
     * @param string|null $eventResult
     *
     * @return $this
     */
    public function setEventResult($eventResult = null)
    {
        $this->eventResult = $eventResult;

        return $this;
    }
}


