<?php
/**
 * HistoryItem
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Server\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Password Manager
 *
 * This is a password manager server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: test@te.st
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the HistoryItem model.
 *
 * @package OpenAPI\Server\Model
 * @author  OpenAPI Generator team
 */
class HistoryItem 
{
        /**
     * @var string|null
     * @SerializedName("UserAgent")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $userAgent;

    /**
     * @var string|null
     * @SerializedName("IP")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $iP;

    /**
     * @var int|null
     * @SerializedName("Time")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $time;

    /**
     * @var string|null
     * @SerializedName("Action")
     * @Assert\Choice({ "Login", "ChangePassword", "Registration" })
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $action;

    /**
     * @var string|null
     * @SerializedName("ActionResult")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $actionResult;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->userAgent = isset($data['userAgent']) ? $data['userAgent'] : null;
        $this->iP = isset($data['iP']) ? $data['iP'] : null;
        $this->time = isset($data['time']) ? $data['time'] : null;
        $this->action = isset($data['action']) ? $data['action'] : null;
        $this->actionResult = isset($data['actionResult']) ? $data['actionResult'] : null;
    }

    /**
     * Gets userAgent.
     *
     * @return string|null
     */
    public function getUserAgent()
    {
        return $this->userAgent;
    }

    /**
     * Sets userAgent.
     *
     * @param string|null $userAgent
     *
     * @return $this
     */
    public function setUserAgent($userAgent = null)
    {
        $this->userAgent = $userAgent;

        return $this;
    }

    /**
     * Gets iP.
     *
     * @return string|null
     */
    public function getIP()
    {
        return $this->iP;
    }

    /**
     * Sets iP.
     *
     * @param string|null $iP
     *
     * @return $this
     */
    public function setIP($iP = null)
    {
        $this->iP = $iP;

        return $this;
    }

    /**
     * Gets time.
     *
     * @return int|null
     */
    public function getTime()
    {
        return $this->time;
    }

    /**
     * Sets time.
     *
     * @param int|null $time
     *
     * @return $this
     */
    public function setTime($time = null)
    {
        $this->time = $time;

        return $this;
    }

    /**
     * Gets action.
     *
     * @return string|null
     */
    public function getAction()
    {
        return $this->action;
    }

    /**
     * Sets action.
     *
     * @param string|null $action
     *
     * @return $this
     */
    public function setAction($action = null)
    {
        $this->action = $action;

        return $this;
    }

    /**
     * Gets actionResult.
     *
     * @return string|null
     */
    public function getActionResult()
    {
        return $this->actionResult;
    }

    /**
     * Sets actionResult.
     *
     * @param string|null $actionResult
     *
     * @return $this
     */
    public function setActionResult($actionResult = null)
    {
        $this->actionResult = $actionResult;

        return $this;
    }
}


