<?php
/**
 * ServerInformation
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Server\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Password Manager
 *
 * This is a password manager server.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: test@te.st
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the ServerInformation model.
 *
 * @package OpenAPI\Server\Model
 * @author  OpenAPI Generator team
 */
class ServerInformation 
{
        /**
     * @var string|null
     * @SerializedName("csrfToken")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $csrfToken;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->csrfToken = isset($data['csrfToken']) ? $data['csrfToken'] : null;
    }

    /**
     * Gets csrfToken.
     *
     * @return string|null
     */
    public function getCsrfToken()
    {
        return $this->csrfToken;
    }

    /**
     * Sets csrfToken.
     *
     * @param string|null $csrfToken
     *
     * @return $this
     */
    public function setCsrfToken($csrfToken = null)
    {
        $this->csrfToken = $csrfToken;

        return $this;
    }
}


