<?php
/**
 * ServerInformation
 *
 * PHP version 7.1.3
 *
 * @category Class
 * @package  OpenAPI\Server\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Password Manager
 *
 * This is a password manager server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: test@te.st
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the ServerInformation model.
 *
 * @package OpenAPI\Server\Model
 * @author  OpenAPI Generator team
 */
class ServerInformation 
{
        /**
     * @var string
     * @SerializedName("csrfToken")
     * @Assert\NotNull()
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $csrfToken;

    /**
     * @var bool|null
     * @SerializedName("allowRegistration")
     * @Assert\Type("bool")
     * @Type("bool")
     */
    protected $allowRegistration;

    /**
     * @var int|null
     * @SerializedName("idleTimeout")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $idleTimeout;

    /**
     * @var string|null
     * @SerializedName("defaultUserConfiguration")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $defaultUserConfiguration;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->csrfToken = isset($data['csrfToken']) ? $data['csrfToken'] : null;
        $this->allowRegistration = isset($data['allowRegistration']) ? $data['allowRegistration'] : null;
        $this->idleTimeout = isset($data['idleTimeout']) ? $data['idleTimeout'] : null;
        $this->defaultUserConfiguration = isset($data['defaultUserConfiguration']) ? $data['defaultUserConfiguration'] : null;
    }

    /**
     * Gets csrfToken.
     *
     * @return string
     */
    public function getCsrfToken()
    {
        return $this->csrfToken;
    }

    /**
     * Sets csrfToken.
     *
     * @param string $csrfToken
     *
     * @return $this
     */
    public function setCsrfToken($csrfToken)
    {
        $this->csrfToken = $csrfToken;

        return $this;
    }

    /**
     * Gets allowRegistration.
     *
     * @return bool|null
     */
    public function isAllowRegistration()
    {
        return $this->allowRegistration;
    }

    /**
     * Sets allowRegistration.
     *
     * @param bool|null $allowRegistration
     *
     * @return $this
     */
    public function setAllowRegistration($allowRegistration = null)
    {
        $this->allowRegistration = $allowRegistration;

        return $this;
    }

    /**
     * Gets idleTimeout.
     *
     * @return int|null
     */
    public function getIdleTimeout()
    {
        return $this->idleTimeout;
    }

    /**
     * Sets idleTimeout.
     *
     * @param int|null $idleTimeout
     *
     * @return $this
     */
    public function setIdleTimeout($idleTimeout = null)
    {
        $this->idleTimeout = $idleTimeout;

        return $this;
    }

    /**
     * Gets defaultUserConfiguration.
     *
     * @return string|null
     */
    public function getDefaultUserConfiguration()
    {
        return $this->defaultUserConfiguration;
    }

    /**
     * Sets defaultUserConfiguration.
     *
     * @param string|null $defaultUserConfiguration
     *
     * @return $this
     */
    public function setDefaultUserConfiguration($defaultUserConfiguration = null)
    {
        $this->defaultUserConfiguration = $defaultUserConfiguration;

        return $this;
    }
}


