<?php
/**
 * UserWebAuthnCreateResponse
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Password Manager
 *
 * This is a password manager server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: test@te.st
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the UserWebAuthnCreateResponse model.
 *
 * @package OpenAPI\Server\Model
 * @author  OpenAPI Generator team
 */
class UserWebAuthnCreateResponse 
{
        /**
     * @var string
     * @SerializedName("attestationObject")
     * @Assert\NotNull()
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $attestationObject;

    /**
     * @var string
     * @SerializedName("clientDataJSON")
     * @Assert\NotNull()
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $clientDataJSON;

    /**
     * @var string
     * @SerializedName("type")
     * @Assert\NotNull()
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $type;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->attestationObject = isset($data['attestationObject']) ? $data['attestationObject'] : null;
        $this->clientDataJSON = isset($data['clientDataJSON']) ? $data['clientDataJSON'] : null;
        $this->type = isset($data['type']) ? $data['type'] : null;
    }

    /**
     * Gets attestationObject.
     *
     * @return string
     */
    public function getAttestationObject()
    {
        return $this->attestationObject;
    }

    /**
     * Sets attestationObject.
     *
     * @param string $attestationObject
     *
     * @return $this
     */
    public function setAttestationObject($attestationObject)
    {
        $this->attestationObject = $attestationObject;

        return $this;
    }

    /**
     * Gets clientDataJSON.
     *
     * @return string
     */
    public function getClientDataJSON()
    {
        return $this->clientDataJSON;
    }

    /**
     * Sets clientDataJSON.
     *
     * @param string $clientDataJSON
     *
     * @return $this
     */
    public function setClientDataJSON($clientDataJSON)
    {
        $this->clientDataJSON = $clientDataJSON;

        return $this;
    }

    /**
     * Gets type.
     *
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Sets type.
     *
     * @param string $type
     *
     * @return $this
     */
    public function setType($type)
    {
        $this->type = $type;

        return $this;
    }
}


