<?php
/**
 * UserSettings
 *
 * PHP version 7.1.3
 *
 * @category Class
 * @package  OpenAPI\Server\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Password Manager
 *
 * This is a password manager server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: test@te.st
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the UserSettings model.
 *
 * @package OpenAPI\Server\Model
 * @author  OpenAPI Generator team
 */
class UserSettings 
{
        /**
     * @var string|null
     * @SerializedName("encryptedUserSettings")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $encryptedUserSettings;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->encryptedUserSettings = isset($data['encryptedUserSettings']) ? $data['encryptedUserSettings'] : null;
    }

    /**
     * Gets encryptedUserSettings.
     *
     * @return string|null
     */
    public function getEncryptedUserSettings()
    {
        return $this->encryptedUserSettings;
    }

    /**
     * Sets encryptedUserSettings.
     *
     * @param string|null $encryptedUserSettings
     *
     * @return $this
     */
    public function setEncryptedUserSettings($encryptedUserSettings = null)
    {
        $this->encryptedUserSettings = $encryptedUserSettings;

        return $this;
    }
}


