<?php
/**
 * UserWebAuthnCreateWithKey
 *
 * PHP version 7.1.3
 *
 * @category Class
 * @package  OpenAPI\Server\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Password Manager
 *
 * This is a password manager server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: test@te.st
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the UserWebAuthnCreateWithKey model.
 *
 * @package OpenAPI\Server\Model
 * @author  OpenAPI Generator team
 */
class UserWebAuthnCreateWithKey 
{
        /**
     * @var string
     * @SerializedName("id")
     * @Assert\NotNull()
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $id;

    /**
     * @var string
     * @SerializedName("name")
     * @Assert\NotNull()
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $name;

    /**
     * @var OpenAPI\Server\Model\UserWebAuthnCreateResponse
     * @SerializedName("response")
     * @Assert\NotNull()
     * @Assert\Type("OpenAPI\Server\Model\UserWebAuthnCreateResponse")
     * @Type("OpenAPI\Server\Model\UserWebAuthnCreateResponse")
     */
    protected $response;

    /**
     * @var string|null
     * @SerializedName("decryptionKey")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $decryptionKey;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->id = isset($data['id']) ? $data['id'] : null;
        $this->name = isset($data['name']) ? $data['name'] : null;
        $this->response = isset($data['response']) ? $data['response'] : null;
        $this->decryptionKey = isset($data['decryptionKey']) ? $data['decryptionKey'] : null;
    }

    /**
     * Gets id.
     *
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Sets id.
     *
     * @param string $id
     *
     * @return $this
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Gets name.
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Sets name.
     *
     * @param string $name
     *
     * @return $this
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Gets response.
     *
     * @return OpenAPI\Server\Model\UserWebAuthnCreateResponse
     */
    public function getResponse(): UserWebAuthnCreateResponse
    {
        return $this->response;
    }

    /**
     * Sets response.
     *
     * @param OpenAPI\Server\Model\UserWebAuthnCreateResponse $response
     *
     * @return $this
     */
    public function setResponse(UserWebAuthnCreateResponse $response)
    {
        $this->response = $response;

        return $this;
    }

    /**
     * Gets decryptionKey.
     *
     * @return string|null
     */
    public function getDecryptionKey()
    {
        return $this->decryptionKey;
    }

    /**
     * Sets decryptionKey.
     *
     * @param string|null $decryptionKey
     *
     * @return $this
     */
    public function setDecryptionKey($decryptionKey = null)
    {
        $this->decryptionKey = $decryptionKey;

        return $this;
    }
}


