<?php
/**
 * UserApiInterface
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Server
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Password Manager
 *
 * This is a password manager server.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: test@te.st
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Api;

use Symfony\Component\HttpFoundation\File\UploadedFile;
use OpenAPI\Server\Model\ChangePassword;
use OpenAPI\Server\Model\GenericSuccessMessage;
use OpenAPI\Server\Model\LogonInformation;
use OpenAPI\Server\Model\RegistrationInformation;

/**
 * UserApiInterface Interface Doc Comment
 *
 * @category Interface
 * @package  OpenAPI\Server\Api
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */
interface UserApiInterface
{

    /**
     * Sets authentication method csrf
     *
     * @param string $value Value of the csrf authentication method.
     *
     * @return void
     */
    public function setcsrf($value);

    /**
     * Operation changePassword
     *
     * change user password
     *
     * @param  OpenAPI\Server\Model\ChangePassword $changePassword  Logon Object (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return OpenAPI\Server\Model\GenericSuccessMessage[]
     *
     */
    public function changePassword(ChangePassword $changePassword, &$responseCode, array &$responseHeaders);

    /**
     * Operation loginUser
     *
     * login
     *
     * @param  OpenAPI\Server\Model\LogonInformation $logonInformation  Logon Object (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return OpenAPI\Server\Model\GenericSuccessMessage[]
     *
     */
    public function loginUser(LogonInformation $logonInformation, &$responseCode, array &$responseHeaders);

    /**
     * Operation logoutUser
     *
     * Logs out current logged in user session
     *
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return OpenAPI\Server\Model\GenericSuccessMessage[]
     *
     */
    public function logoutUser(&$responseCode, array &$responseHeaders);

    /**
     * Operation registerUser
     *
     * registration
     *
     * @param  OpenAPI\Server\Model\RegistrationInformation $registrationInformation  Registration Object (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return OpenAPI\Server\Model\GenericSuccessMessage[]
     *
     */
    public function registerUser(RegistrationInformation $registrationInformation, &$responseCode, array &$responseHeaders);
}
