kind: pipeline
type: docker
name: build
steps:
 - name: restore caches
   when:
     event:
       exclude:
       - promote
   image: plugins/s3-cache
   settings:
     pull: true
     endpoint: http://minio:9000
     access_key: 
       from_secret: "s3_access_key"
     secret_key: 
       from_secret: "s3_secret_key"
     restore: true
 - name: react
   when:
     event:
       exclude:
       - promote
   image: node:12
   commands:
    - cd reactClient/my-app
    - npm ci --cache ../../.npm --prefer-offline
    - npm link --unsafe-perm ../../OpenAPIReactClient
    - CI="" npm run build
 - name: cache build for deployment
   when:
     event:
       exclude:
       - promote
   image: plugins/s3-cache
   settings:
     pull: true
     endpoint: http://minio:9000
     access_key: 
       from_secret: "s3_access_key"
     secret_key: 
       from_secret: "s3_secret_key"
     filename: "${DRONE_COMMIT}.tar"
     rebuild: true
     mount:
       - reactClient/my-app/build
 - name: restore caches for deployment
   when:
     event:
     - promote
   image: plugins/s3-cache
   settings:
     pull: true
     endpoint: http://minio:9000
     access_key: 
       from_secret: "s3_access_key"
     secret_key: 
       from_secret: "s3_secret_key"
     restore: true
     filename: "${DRONE_COMMIT}.tar"
 - name: symfony
   image: php:8.1
   commands:
    - apt-get update && apt-get install -y libzip-dev zip && docker-php-ext-install zip
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php composer-setup.php --quiet
    - cd ./Symfony-API
    - php ../composer.phar install --no-suggest --no-dev --no-progress --optimize-autoloader --classmap-authoritative
    - (cd vendor/openapi && rm -r server-bundle && cp -r ../../../OpenAPIServerBundle/ server-bundle)
    - cp -r ../reactClient/my-app/build/. public/
    #- rm ./templates/base.html.twig && ln -s ../public/index.html ./templates/index.html
    - cp ../dockerBuild/SymfonyDockerfile Dockerfile
 - name: cache stuff
   when:
     event:
       exclude:
       - promote
   image: plugins/s3-cache
   settings:
     pull: true
     endpoint: http://minio:9000
     access_key: 
       from_secret: "s3_access_key"
     secret_key: 
       from_secret: "s3_secret_key"
     rebuild: true
     mount:
       - .npm
       - Symfony-API/vendor
 - name: flush cache older than 14 days
   when:
     event:
       exclude:
       - promote
   image: plugins/s3-cache
   settings:
     pull: true
     endpoint: http://minio:9000
     access_key: 
       from_secret: "s3_access_key"
     secret_key: 
       from_secret: "s3_secret_key"
     flush: true
     flush_age: 14
 - name: "deploy to environment ${DRONE_DEPLOY_TO}"
   image: alpine:3.12
   environment:
     SSH_PRIVATE_KEY:
       from_secret: "${DRONE_DEPLOY_TO}_ssh_private_key"
     SSH_HOST:
       from_secret: "${DRONE_DEPLOY_TO}_ssh_host"
     SSH_USER:
       from_secret: "${DRONE_DEPLOY_TO}_ssh_user"
     SSH_HOST_KEY:
       from_secret: "${DRONE_DEPLOY_TO}_ssh_host_key"
     DEPLOY_PATH: "~/htdocs/pwman-${DRONE_DEPLOY_TO}/"
     COPY_PATH: "~/tmp/mpm.zip"
     COPY_REMOTE_PATH: "tmp/"
     DEV_PHP_VERSION: "php8.1"
     TEST_PHP_VERSION: "php8.1"
     PROD_PHP_VERSION: "php8.1"
   commands:
     - export PHP_VERSION=$${${DRONE_DEPLOY_TO^^}_PHP_VERSION}
     - echo $${PHP_VERSION}
     - . ./drone_scripts/deploy.sh
   when:
     event:
      - promote
     target:
      - test
      - prod
