kind: pipeline
type: docker
name: build
steps:
 - name: react
   image: node:12
   docker:
     user: 1000
   commands:
    - cd reactClient/my-app
    - npm install
    - npm link ../../OpenAPIReactClient
    - CI="" npm run build
    
