kind: pipeline
type: docker
name: build
steps:
 - name: react
   image: node:12
   commands:
    - cd reactClient/my-app
    - npm install
    - npm link --unsafe-perm ../../OpenAPIReactClient
    - CI="" npm run build
 - name: symfony
   image: composer:2
   commands:
    - cd ./Symfony-API
    - composer -q install --no-suggest --no-dev --no-progress --optimize-autoloader --classmap-authoritative
    - (cd vendor/openapi && rm server-bundle && cp -r ../../../OpenAPIServerBundle/ server-bundle)
    - cp -r ../reactClient/my-app/build/. public/
    - rm ./templates/base.html.twig && ln -s ../public/index.html ./templates/index.html
    - cp ../dockerBuild/SymfonyDockerfile Dockerfile
 - name: deploy to test
   image: alpine:3.12
   environment:
     SSH_PRIVATE_KEY:
       from_secret: ssh_private_key
     SSH_HOST:
       from_secret: ssh_host
     SSH_USER:
       from_secret: ssh_user
     SSH_HOST_KEY:
       from_secret: ssh_host_key
     PHP_VERSION:
       from_secret: php_version
   commands:
     - apk update
     - apk add zip openssh-client
    # setup ssh
     - mkdir ~/.ssh
     - echo $${SSH_PRIVATE_KEY} | base64 -d > ~/.ssh/id_drone
     - chmod 0600 ~/.ssh/id_drone
     - echo $${SSH_HOST_KEY} | base64 -d > ~/.ssh/known_hosts
     - chmod 0600 ~/.ssh/known_hosts
    # create zip archive
     - zip -q --symlinks -r mpm.zip ./Symfony-API
    # transfer to host
     - scp -i ~/.ssh/id_drone mpm.zip "$${SSH_USER}@$${SSH_HOST}:tmp/"
    # extract to destination
     - ssh -i ~/.ssh/id_drone "$${SSH_USER}@$${SSH_HOST}" 'cd ~/tmp; unzip -q mpm.zip -o -d ~/htdocs/pwman/'
    # execute db update
     - ssh -i ~/.ssh/id_drone "$${SSH_USER}@$${SSH_HOST}" 'cd ~/htdocs/pwman/Symfony-API && echo ${PHP_VERSION} bin/console doctrine:schema:update --force && echo ${PHP_VERSION} bin/console cache:clear'
   #when:
     #event:
     # - promote
     #target:
     # - test     
