kind: pipeline
type: docker
name: build
steps:
 - name: react
   image: node:12
   commands:
    - cd reactClient/my-app
    - npm install
    - npm link --unsafe-perm ../../OpenAPIReactClient
    - CI="" npm run build
    
