/**
 * Password Manager
 * This is a password manager server.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: test@te.st
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Account } from './account';
import { Index } from './index';


export interface AccountId { 
    index?: number;
    name?: string;
    additional?: string;
    password?: string;
}

