/**
 * Password Manager
 * This is a password manager server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: test@te.st
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserInformation } from './userInformation';
import { LogonInformation } from './logonInformation';


export interface RegistrationInformation { 
    username?: string;
    password?: string;
    email?: string;
}

