/* tslint:disable */
/* eslint-disable */
/**
 * Password Manager
 * This is a password manager server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: test@te.st
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Account,
    AccountFromJSON,
    AccountFromJSONTyped,
    AccountToJSON,
    ModelIndex,
    ModelIndexFromJSON,
    ModelIndexFromJSONTyped,
    ModelIndexToJSON,
} from './';

/**
 * 
 * @export
 * @interface AccountId
 */
export interface AccountId {
    /**
     * 
     * @type {number}
     * @memberof AccountId
     */
    index?: number;
    /**
     * 
     * @type {string}
     * @memberof AccountId
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof AccountId
     */
    additional?: string;
    /**
     * 
     * @type {string}
     * @memberof AccountId
     */
    password?: string;
}

export function AccountIdFromJSON(json: any): AccountId {
    return AccountIdFromJSONTyped(json, false);
}

export function AccountIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountId {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'index': !exists(json, 'index') ? undefined : json['index'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'additional': !exists(json, 'additional') ? undefined : json['additional'],
        'password': !exists(json, 'password') ? undefined : json['password'],
    };
}

export function AccountIdToJSON(value?: AccountId | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'index': value.index,
        'name': value.name,
        'additional': value.additional,
        'password': value.password,
    };
}


