/* tslint:disable */
/* eslint-disable */
/**
 * Password Manager
 * This is a password manager server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: test@te.st
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DecryptionKey
 */
export interface DecryptionKey {
    /**
     * 
     * @type {string}
     * @memberof DecryptionKey
     */
    decryptionKey?: string;
}

export function DecryptionKeyFromJSON(json: any): DecryptionKey {
    return DecryptionKeyFromJSONTyped(json, false);
}

export function DecryptionKeyFromJSONTyped(json: any, ignoreDiscriminator: boolean): DecryptionKey {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'decryptionKey': !exists(json, 'decryptionKey') ? undefined : json['decryptionKey'],
    };
}

export function DecryptionKeyToJSON(value?: DecryptionKey | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'decryptionKey': value.decryptionKey,
    };
}


