// tslint:disable
// eslint-disable
/**
 * Password Manager
 * This is a password manager server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: test@te.st
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Index
 */
export interface Index {
    /**
     * 
     * @type {number}
     * @memberof Index
     */
    index?: number;
}

export function IndexFromJSON(json: any): Index {
    return IndexFromJSONTyped(json, false);
}

export function IndexFromJSONTyped(json: any, ignoreDiscriminator: boolean): Index {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'index': !exists(json, 'index') ? undefined : json['index'],
    };
}

export function IndexToJSON(value?: Index | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'index': value.index,
    };
}


