/* tslint:disable */
/* eslint-disable */
/**
 * Password Manager
 * This is a password manager server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: test@te.st
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelIndex
 */
export interface ModelIndex {
    /**
     * 
     * @type {number}
     * @memberof ModelIndex
     */
    index: number;
}

export function ModelIndexFromJSON(json: any): ModelIndex {
    return ModelIndexFromJSONTyped(json, false);
}

export function ModelIndexFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelIndex {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'index': json['index'],
    };
}

export function ModelIndexToJSON(value?: ModelIndex | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'index': value.index,
    };
}


