/* tslint:disable */
/* eslint-disable */
/**
 * Password Manager
 * This is a password manager server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: test@te.st
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServerInformation
 */
export interface ServerInformation {
    /**
     * 
     * @type {string}
     * @memberof ServerInformation
     */
    csrfToken: string;
    /**
     * 
     * @type {boolean}
     * @memberof ServerInformation
     */
    allowRegistration?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ServerInformation
     */
    idleTimeout?: number;
    /**
     * 
     * @type {string}
     * @memberof ServerInformation
     */
    defaultUserConfiguration?: string;
    /**
     * 
     * @type {string}
     * @memberof ServerInformation
     */
    webAuthNChallenge?: string;
}

export function ServerInformationFromJSON(json: any): ServerInformation {
    return ServerInformationFromJSONTyped(json, false);
}

export function ServerInformationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServerInformation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'csrfToken': json['csrfToken'],
        'allowRegistration': !exists(json, 'allowRegistration') ? undefined : json['allowRegistration'],
        'idleTimeout': !exists(json, 'idleTimeout') ? undefined : json['idleTimeout'],
        'defaultUserConfiguration': !exists(json, 'defaultUserConfiguration') ? undefined : json['defaultUserConfiguration'],
        'webAuthNChallenge': !exists(json, 'webAuthNChallenge') ? undefined : json['webAuthNChallenge'],
    };
}

export function ServerInformationToJSON(value?: ServerInformation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'csrfToken': value.csrfToken,
        'allowRegistration': value.allowRegistration,
        'idleTimeout': value.idleTimeout,
        'defaultUserConfiguration': value.defaultUserConfiguration,
        'webAuthNChallenge': value.webAuthNChallenge,
    };
}


