/* tslint:disable */
/* eslint-disable */
/**
 * Password Manager
 * This is a password manager server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: test@te.st
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserWebAuthnCred
 */
export interface UserWebAuthnCred {
    /**
     * 
     * @type {string}
     * @memberof UserWebAuthnCred
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof UserWebAuthnCred
     */
    id: number;
    /**
     * 
     * @type {Date}
     * @memberof UserWebAuthnCred
     */
    lastUsed?: Date;
}

export function UserWebAuthnCredFromJSON(json: any): UserWebAuthnCred {
    return UserWebAuthnCredFromJSONTyped(json, false);
}

export function UserWebAuthnCredFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserWebAuthnCred {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'id': json['id'],
        'lastUsed': !exists(json, 'lastUsed') ? undefined : (new Date(json['lastUsed'])),
    };
}

export function UserWebAuthnCredToJSON(value?: UserWebAuthnCred | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'id': value.id,
        'lastUsed': value.lastUsed === undefined ? undefined : (value.lastUsed.toISOString()),
    };
}


