/* tslint:disable */
/* eslint-disable */
/**
 * Password Manager
 * This is a password manager server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: test@te.st
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserWebAuthnChallenge
 */
export interface UserWebAuthnChallenge {
    /**
     * 
     * @type {string}
     * @memberof UserWebAuthnChallenge
     */
    challenge: string;
}

export function UserWebAuthnChallengeFromJSON(json: any): UserWebAuthnChallenge {
    return UserWebAuthnChallengeFromJSONTyped(json, false);
}

export function UserWebAuthnChallengeFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserWebAuthnChallenge {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'challenge': json['challenge'],
    };
}

export function UserWebAuthnChallengeToJSON(value?: UserWebAuthnChallenge | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'challenge': value.challenge,
    };
}

