/* tslint:disable */
/* eslint-disable */
/**
 * Password Manager
 * This is a password manager server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: test@te.st
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserWebAuthnGetResponse
 */
export interface UserWebAuthnGetResponse {
    /**
     * 
     * @type {string}
     * @memberof UserWebAuthnGetResponse
     */
    authenticatorData: string;
    /**
     * 
     * @type {string}
     * @memberof UserWebAuthnGetResponse
     */
    clientDataJSON: string;
    /**
     * 
     * @type {string}
     * @memberof UserWebAuthnGetResponse
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof UserWebAuthnGetResponse
     */
    signature: string;
}

export function UserWebAuthnGetResponseFromJSON(json: any): UserWebAuthnGetResponse {
    return UserWebAuthnGetResponseFromJSONTyped(json, false);
}

export function UserWebAuthnGetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserWebAuthnGetResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'authenticatorData': json['authenticatorData'],
        'clientDataJSON': json['clientDataJSON'],
        'type': json['type'],
        'signature': json['signature'],
    };
}

export function UserWebAuthnGetResponseToJSON(value?: UserWebAuthnGetResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'authenticatorData': value.authenticatorData,
        'clientDataJSON': value.clientDataJSON,
        'type': value.type,
        'signature': value.signature,
    };
}


