/* tslint:disable */
/* eslint-disable */
/**
 * Password Manager
 * This is a password manager server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: test@te.st
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserWebAuthnCreateResponse
 */
export interface UserWebAuthnCreateResponse {
    /**
     * 
     * @type {string}
     * @memberof UserWebAuthnCreateResponse
     */
    attestationObject: string;
    /**
     * 
     * @type {string}
     * @memberof UserWebAuthnCreateResponse
     */
    clientDataJSON: string;
    /**
     * 
     * @type {string}
     * @memberof UserWebAuthnCreateResponse
     */
    type: string;
}

export function UserWebAuthnCreateResponseFromJSON(json: any): UserWebAuthnCreateResponse {
    return UserWebAuthnCreateResponseFromJSONTyped(json, false);
}

export function UserWebAuthnCreateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserWebAuthnCreateResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'attestationObject': json['attestationObject'],
        'clientDataJSON': json['clientDataJSON'],
        'type': json['type'],
    };
}

export function UserWebAuthnCreateResponseToJSON(value?: UserWebAuthnCreateResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'attestationObject': value.attestationObject,
        'clientDataJSON': value.clientDataJSON,
        'type': value.type,
    };
}

