/* tslint:disable */
/* eslint-disable */
/**
 * Password Manager
 * This is a password manager server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: test@te.st
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DecryptionKey,
    DecryptionKeyFromJSON,
    DecryptionKeyFromJSONTyped,
    DecryptionKeyToJSON,
    LogonResult,
    LogonResultFromJSON,
    LogonResultFromJSONTyped,
    LogonResultToJSON,
} from './';

/**
 * 
 * @export
 * @interface UserWebAuthnLogonResult
 */
export interface UserWebAuthnLogonResult {
    /**
     * 
     * @type {boolean}
     * @memberof UserWebAuthnLogonResult
     */
    success: boolean;
    /**
     * 
     * @type {string}
     * @memberof UserWebAuthnLogonResult
     */
    message: string;
    /**
     * 
     * @type {Date}
     * @memberof UserWebAuthnLogonResult
     */
    lastLogin?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof UserWebAuthnLogonResult
     */
    failedLogins?: number;
    /**
     * 
     * @type {string}
     * @memberof UserWebAuthnLogonResult
     */
    decryptionKey?: string;
}

export function UserWebAuthnLogonResultFromJSON(json: any): UserWebAuthnLogonResult {
    return UserWebAuthnLogonResultFromJSONTyped(json, false);
}

export function UserWebAuthnLogonResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserWebAuthnLogonResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': json['success'],
        'message': json['message'],
        'lastLogin': !exists(json, 'lastLogin') ? undefined : (json['lastLogin'] === null ? null : new Date(json['lastLogin'])),
        'failedLogins': !exists(json, 'failedLogins') ? undefined : json['failedLogins'],
        'decryptionKey': !exists(json, 'decryptionKey') ? undefined : json['decryptionKey'],
    };
}

export function UserWebAuthnLogonResultToJSON(value?: UserWebAuthnLogonResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'message': value.message,
        'lastLogin': value.lastLogin === undefined ? undefined : (value.lastLogin === null ? null : value.lastLogin.toISOString()),
        'failedLogins': value.failedLogins,
        'decryptionKey': value.decryptionKey,
    };
}


