/* tslint:disable */
/* eslint-disable */
/**
 * Password Manager
 * This is a password manager server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: test@te.st
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    UserWebAuthnGetResponse,
    UserWebAuthnGetResponseFromJSON,
    UserWebAuthnGetResponseFromJSONTyped,
    UserWebAuthnGetResponseToJSON,
} from './';

/**
 * 
 * @export
 * @interface UserWebAuthnGet
 */
export interface UserWebAuthnGet {
    /**
     * 
     * @type {string}
     * @memberof UserWebAuthnGet
     */
    id: string;
    /**
     * 
     * @type {UserWebAuthnGetResponse}
     * @memberof UserWebAuthnGet
     */
    response: UserWebAuthnGetResponse;
}

export function UserWebAuthnGetFromJSON(json: any): UserWebAuthnGet {
    return UserWebAuthnGetFromJSONTyped(json, false);
}

export function UserWebAuthnGetFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserWebAuthnGet {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'response': UserWebAuthnGetResponseFromJSON(json['response']),
    };
}

export function UserWebAuthnGetToJSON(value?: UserWebAuthnGet | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'response': UserWebAuthnGetResponseToJSON(value.response),
    };
}


