/* tslint:disable */
/* eslint-disable */
/**
 * Password Manager
 * This is a password manager server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: test@te.st
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserInformation
 */
export interface UserInformation {
    /**
     * 
     * @type {string}
     * @memberof UserInformation
     */
    email?: string;
}

export function UserInformationFromJSON(json: any): UserInformation {
    return UserInformationFromJSONTyped(json, false);
}

export function UserInformationFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserInformation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': !exists(json, 'email') ? undefined : json['email'],
    };
}

export function UserInformationToJSON(value?: UserInformation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
    };
}


