/* tslint:disable */
/* eslint-disable */
/**
 * Password Manager
 * This is a password manager server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: test@te.st
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    UserWebAuthnCreateResponse,
    UserWebAuthnCreateResponseFromJSON,
    UserWebAuthnCreateResponseFromJSONTyped,
    UserWebAuthnCreateResponseToJSON,
} from './';

/**
 * 
 * @export
 * @interface UserWebAuthnCreate
 */
export interface UserWebAuthnCreate {
    /**
     * 
     * @type {string}
     * @memberof UserWebAuthnCreate
     */
    id: string;
    /**
     * 
     * @type {UserWebAuthnCreateResponse}
     * @memberof UserWebAuthnCreate
     */
    response: UserWebAuthnCreateResponse;
}

export function UserWebAuthnCreateFromJSON(json: any): UserWebAuthnCreate {
    return UserWebAuthnCreateFromJSONTyped(json, false);
}

export function UserWebAuthnCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserWebAuthnCreate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'response': UserWebAuthnCreateResponseFromJSON(json['response']),
    };
}

export function UserWebAuthnCreateToJSON(value?: UserWebAuthnCreate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'response': UserWebAuthnCreateResponseToJSON(value.response),
    };
}


