/**
 * Password Manager
 * This is a password manager server.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: test@te.st
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { ChangePassword } from '../model/changePassword';
import { GenericSuccessMessage } from '../model/genericSuccessMessage';
import { LogonInformation } from '../model/logonInformation';
import { RegistrationInformation } from '../model/registrationInformation';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable({
  providedIn: 'root'
})
export class UserService {

    protected basePath = 'http://localhost';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {

        if (configuration) {
            this.configuration = configuration;
            this.configuration.basePath = configuration.basePath || basePath || this.basePath;

        } else {
            this.configuration.basePath = basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * change user password
     * change password of current user and upload reencrypted accounts
     * @param changePassword Logon Object
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public changePassword(changePassword: ChangePassword, observe?: 'body', reportProgress?: boolean): Observable<GenericSuccessMessage>;
    public changePassword(changePassword: ChangePassword, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<GenericSuccessMessage>>;
    public changePassword(changePassword: ChangePassword, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<GenericSuccessMessage>>;
    public changePassword(changePassword: ChangePassword, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (changePassword === null || changePassword === undefined) {
            throw new Error('Required parameter changePassword was null or undefined when calling changePassword.');
        }

        let headers = this.defaultHeaders;

        // authentication (csrf) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["X-CSRF-TOKEN"]) {
            headers = headers.set('X-CSRF-TOKEN', this.configuration.apiKeys["X-CSRF-TOKEN"]);
        }

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<GenericSuccessMessage>(`${this.configuration.basePath}/user/changepassword`,
            changePassword,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * login
     * 
     * @param logonInformation Logon Object
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public loginUser(logonInformation: LogonInformation, observe?: 'body', reportProgress?: boolean): Observable<GenericSuccessMessage>;
    public loginUser(logonInformation: LogonInformation, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<GenericSuccessMessage>>;
    public loginUser(logonInformation: LogonInformation, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<GenericSuccessMessage>>;
    public loginUser(logonInformation: LogonInformation, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (logonInformation === null || logonInformation === undefined) {
            throw new Error('Required parameter logonInformation was null or undefined when calling loginUser.');
        }

        let headers = this.defaultHeaders;

        // authentication (csrf) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["X-CSRF-TOKEN"]) {
            headers = headers.set('X-CSRF-TOKEN', this.configuration.apiKeys["X-CSRF-TOKEN"]);
        }

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<GenericSuccessMessage>(`${this.configuration.basePath}/user/login`,
            logonInformation,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Logs out current logged in user session
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public logoutUser(observe?: 'body', reportProgress?: boolean): Observable<GenericSuccessMessage>;
    public logoutUser(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<GenericSuccessMessage>>;
    public logoutUser(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<GenericSuccessMessage>>;
    public logoutUser(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<GenericSuccessMessage>(`${this.configuration.basePath}/user/logout`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * registration
     * 
     * @param registrationInformation Registration Object
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public registerUser(registrationInformation: RegistrationInformation, observe?: 'body', reportProgress?: boolean): Observable<GenericSuccessMessage>;
    public registerUser(registrationInformation: RegistrationInformation, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<GenericSuccessMessage>>;
    public registerUser(registrationInformation: RegistrationInformation, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<GenericSuccessMessage>>;
    public registerUser(registrationInformation: RegistrationInformation, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (registrationInformation === null || registrationInformation === undefined) {
            throw new Error('Required parameter registrationInformation was null or undefined when calling registerUser.');
        }

        let headers = this.defaultHeaders;

        // authentication (csrf) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["X-CSRF-TOKEN"]) {
            headers = headers.set('X-CSRF-TOKEN', this.configuration.apiKeys["X-CSRF-TOKEN"]);
        }

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<GenericSuccessMessage>(`${this.configuration.basePath}/user`,
            registrationInformation,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
