doctrine_migrations:
    # namespace is arbitrary but should be different from App\Migrations
    # as migrations classes should NOT be autoloaded
    migrations_paths:
            'DoctrineMigrations': '%kernel.project_dir%/src/Migrations'
