<?php
/**
 * UserApiInterfaceTest
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server\Tests\Api
 * @author   openapi-generator contributors
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Password Manager
 *
 * This is a password manager server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: test@te.st
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Server\Tests\Api;

use OpenAPI\Server\Configuration;
use OpenAPI\Server\ApiClient;
use OpenAPI\Server\ApiException;
use OpenAPI\Server\ObjectSerializer;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

/**
 * UserApiInterfaceTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Server\Tests\Api
 * @author   openapi-generator contributors
 * @link     https://github.com/openapitools/openapi-generator
 */
class UserApiInterfaceTest extends WebTestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for changePassword
     *
     * change user password.
     *
     */
    public function testChangePassword()
    {
        $client = static::createClient();

        $path = '/user/changepassword';

        $crawler = $client->request('POST', $path, [], [], ['CONTENT_TYPE' => 'application/json']);
    }

    /**
     * Test case for createUserWebAuthn
     *
     * add a webauthn credential.
     *
     */
    public function testCreateUserWebAuthn()
    {
        $client = static::createClient();

        $path = '/user/webauthn';

        $crawler = $client->request('POST', $path, [], [], ['CONTENT_TYPE' => 'application/json']);
    }

    /**
     * Test case for deleteUserWebAuthn
     *
     * Delete a stored WebAuthn Public Key.
     *
     */
    public function testDeleteUserWebAuthn()
    {
        $client = static::createClient();

        $path = '/user/webauthn/{id}';
        $pattern = '{id}';
        $data = $this->genTestData('\d+');
        $path = str_replace($pattern, $data, $path);

        $crawler = $client->request('DELETE', $path);
    }

    /**
     * Test case for getUserHistory
     *
     * Returns a history of successful and failed logins.
     *
     */
    public function testGetUserHistory()
    {
        $client = static::createClient();

        $path = '/user/history';

        $crawler = $client->request('GET', $path);
    }

    /**
     * Test case for getUserSettings
     *
     * Returns the client settings of the current user.
     *
     */
    public function testGetUserSettings()
    {
        $client = static::createClient();

        $path = '/user/settings';

        $crawler = $client->request('GET', $path);
    }

    /**
     * Test case for getUserWebAuthnCreds
     *
     * get all registered WebAuthn credentials for the user.
     *
     */
    public function testGetUserWebAuthnCreds()
    {
        $client = static::createClient();

        $path = '/user/webauthn';

        $crawler = $client->request('GET', $path);
    }

    /**
     * Test case for loginUser
     *
     * login.
     *
     */
    public function testLoginUser()
    {
        $client = static::createClient();

        $path = '/user/login';

        $crawler = $client->request('POST', $path, [], [], ['CONTENT_TYPE' => 'application/json']);
    }

    /**
     * Test case for loginUserWebAuthnChallenge
     *
     * get a WebAuthN challenge.
     *
     */
    public function testLoginUserWebAuthnChallenge()
    {
        $client = static::createClient();

        $path = '/user/login/webauthn';

        $crawler = $client->request('GET', $path);
    }

    /**
     * Test case for loginUserWebAuthnGet
     *
     * login user with WebAuthn.
     *
     */
    public function testLoginUserWebAuthnGet()
    {
        $client = static::createClient();

        $path = '/user/login/webauthn';

        $crawler = $client->request('POST', $path, [], [], ['CONTENT_TYPE' => 'application/json']);
    }

    /**
     * Test case for logoutUser
     *
     * Logs out current logged in user session.
     *
     */
    public function testLogoutUser()
    {
        $client = static::createClient();

        $path = '/user/logout';

        $crawler = $client->request('GET', $path);
    }

    /**
     * Test case for registerUser
     *
     * registration.
     *
     */
    public function testRegisterUser()
    {
        $client = static::createClient();

        $path = '/user';

        $crawler = $client->request('PUT', $path, [], [], ['CONTENT_TYPE' => 'application/json']);
    }

    /**
     * Test case for setUserSettings
     *
     * change client settings of current user.
     *
     */
    public function testSetUserSettings()
    {
        $client = static::createClient();

        $path = '/user/settings';

        $crawler = $client->request('POST', $path, [], [], ['CONTENT_TYPE' => 'application/json']);
    }

    protected function genTestData($regexp)
    {
        $grammar  = new \Hoa\File\Read('hoa://Library/Regex/Grammar.pp');
        $compiler = \Hoa\Compiler\Llk\Llk::load($grammar);
        $ast      = $compiler->parse($regexp);
        $generator = new \Hoa\Regex\Visitor\Isotropic(new \Hoa\Math\Sampler\Random());

        return $generator->visit($ast);
    }
}
