/* tslint:disable */
/* eslint-disable */
/**
 * Password Manager
 * This is a password manager server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: test@te.st
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    ServerInformation,
    ServerInformationFromJSON,
    ServerInformationToJSON,
} from '../models';

/**
 * 
 */
export class MaintenanceApi extends runtime.BaseAPI {

    /**
     * get information about the server for the client
     */
    async serverInformationRaw(): Promise<runtime.ApiResponse<ServerInformation>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/info`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => ServerInformationFromJSON(jsonValue));
    }

    /**
     * get information about the server for the client
     */
    async serverInformation(): Promise<ServerInformation> {
        const response = await this.serverInformationRaw();
        return await response.value();
    }

}
