<?php
/**
 * ServerInformationTest
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server\Tests\Model
 * @author   openapi-generator contributors
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Password Manager
 *
 * This is a password manager server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: test@te.st
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Server\Model;

use PHPUnit\Framework\TestCase;

/**
 * ServerInformationTest Class Doc Comment
 *
 * @category    Class */
// * @description ServerInformation
/**
 * @package     OpenAPI\Server\Tests\Model
 * @author      openapi-generator contributors
 * @link        https://github.com/openapitools/openapi-generator
 */
class ServerInformationTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ServerInformation"
     */
    public function testServerInformation()
    {
        $testServerInformation = new ServerInformation();
    }

    /**
     * Test attribute "csrfToken"
     */
    public function testPropertyCsrfToken()
    {
    }

    /**
     * Test attribute "allowRegistration"
     */
    public function testPropertyAllowRegistration()
    {
    }

    /**
     * Test attribute "idleTimeout"
     */
    public function testPropertyIdleTimeout()
    {
    }

    /**
     * Test attribute "defaultUserConfiguration"
     */
    public function testPropertyDefaultUserConfiguration()
    {
    }

    /**
     * Test attribute "webAuthNChallenge"
     */
    public function testPropertyWebAuthNChallenge()
    {
    }
}
