<?php
/**
 * UserWebAuthnCreateResponseTest
 *
 * PHP version 7.1.3
 *
 * @category Class
 * @package  OpenAPI\Server\Tests\Model
 * @author   openapi-generator contributors
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Password Manager
 *
 * This is a password manager server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: test@te.st
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Server\Model;

use PHPUnit\Framework\TestCase;

/**
 * UserWebAuthnCreateResponseTest Class Doc Comment
 *
 * @category    Class */
// * @description UserWebAuthnCreateResponse
/**
 * @package     OpenAPI\Server\Tests\Model
 * @author      openapi-generator contributors
 * @link        https://github.com/openapitools/openapi-generator
 */
class UserWebAuthnCreateResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "UserWebAuthnCreateResponse"
     */
    public function testUserWebAuthnCreateResponse()
    {
        $testUserWebAuthnCreateResponse = new UserWebAuthnCreateResponse();
    }

    /**
     * Test attribute "attestationObject"
     */
    public function testPropertyAttestationObject()
    {
    }

    /**
     * Test attribute "clientDataJSON"
     */
    public function testPropertyClientDataJSON()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }
}
