name: build application
on: [push]

jobs:
  build_react:
    name: build react app 
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install
        working-directory: ./reactClient/my-app/
      - run: npm link ../../OpenAPIReactClient/
        working-directory: ./reactClient/my-app/
      - run: npm run build
        working-directory: ./reactClient/my-app/
        env:
          CI: ""
      - uses: actions/upload-artifact@v2
        with:
          name: react-build
          path: reactClient/my-app/build/
  build_symfony:
    name: build symfony
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Run composer install
        uses: php-actions/composer@v1
        with: 
          command: install -d=./Symfony-API/
      - name: Insert ReactJS files
        uses: actions/download-artifact@v2
        with:
          name: react-build
          path: Symfony-API/public/
      - name: show files
        run: ls -la
        working-directory: ./Symfony-API/public/
      - uses: actions/upload-artifact@v2
        with:
          name: symfony-project
          path: Symfony-API/
