name: build application
on: [push]

jobs:
  build_react:
    name: build react app 
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install
        working-directory: ./reactClient/my-app/
      - run: npm link ../../OpenAPIReactClient/
        working-directory: ./reactClient/my-app/
      - run: npm run build
        working-directory: ./reactClient/my-app/
        env:
          CI: ""
      - uses: actions/upload-artifact@v2
        with:
          name: react-build
          path: reactClient/my-app/build/
  build_symfony:
    name: build symfony
    needs: build_react
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer
      - name: Run composer install
        run: composer install --no-suggest --no-dev --no-progress
        working-directory: ./Symfony-API/
      - name: Insert ReactJS files
        uses: actions/download-artifact@v2
        with:
          name: react-build
          path: Symfony-API/public/
      - name: copy index.html of react to template
        run: "rm ./templates/base.html.twig && cp ./public/index.html ./templates/"
        working-directory: ./Symfony-API/
      - uses: actions/upload-artifact@v2
        with:
          name: symfony-project
          path: Symfony-API/
