name: linting
on: [push]

jobs:
  build:
    name: lint 
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Super-Linter
        uses: github/super-linter@v2.1.0
