name: linting
on: [push]

jobs:
  build:
    name: lint 
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: "install"
        run: npm install eslint
        working-directory: ./reactClient/my-app
      - name: "lint"
        run: npm run lint
        working-directory: ./reactClient/my-app
