name: linting
on: [push]

jobs:
  build:
    name: lint 
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Lint: React
        uses: github/super-linter@v2.1.0
        working-directory: ./reactClient/
      - name: Lint: Symfony
        uses: github/super-linter@v2.1.0
        working-directory: ./Symfony-API/
